application: mupl-py
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version : "1.4"
handlers:
- url: /static
  static_dir: static
-url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: mupl_web.wsgi.application
